# Q1

In [2]:
from scipy import stats 
import pandas as pd
import numpy as np
import math as mt

%matplotlib inline 
import warnings
warnings.filterwarnings('ignore')

In [6]:
df = pd.read_csv('cutlets.csv')
df.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [11]:
stats.ttest_ind(df['Unit A'],df['Unit B'])

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

# Q2

In [12]:
import scipy.stats as stats

In [13]:
df1 = pd.read_csv('LabTAT.csv')
df1.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [18]:
stats.f_oneway(df1.iloc[:,0], df1.iloc[:,1], df1.iloc[:,2], df1.iloc[:,3])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

# Q3

In [20]:
!pip install bioinfokit

     ---------------------------------------- 87.0/87.0 kB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for bioinfokit: filename=bioinfokit-2.1.0-py3-none-any.whl size=58669 sha256=53c8c840c9e61611d65773e16830417203657c5ffb7623a9712b91a2cc776109
  Stored in directory: c:\users\dell\appdata\local\pip\cache\wheels\c9\ab\ed\8a7fde0a63653b75ac029d67598265d185e5915dfb594ddc59
  Created wheel for adjustText: filename=adjustText-0.7.3-py3-none-any.whl size=7074 sha256=2e7bdbdb063931f119218d7d123c6fe6c8f70eb6324064fad2ffadecf9e7cb54
  Stored in directory: c:\users\dell\appdata\local\pip\cache\wheels\6b\1d\79\4326d5f3a7d86fb9900e5564e7a0f98b552da5103ca762f24f
  Created wheel for matplotlib-venn: filena

In [21]:
from bioinfokit.analys import stat

In [36]:
df2 = pd.read_csv('BuyerRatio.csv')
df2.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [38]:
data = pd.DataFrame([
    [50,142,131,70],
    [435,1523,1356,750]],
    index = ['Male','Females'], columns = ['East','West','North','South'])
data



East  West  North  South
Male       50   142    131     70
Females   435  1523   1356    750

In [39]:
res = stat()
res.chisq(df=data)
print(res.summary)


Chi-squared test for independence

Test              Df    Chi-square    P-value
--------------  ----  ------------  ---------
Pearson            3       1.59595   0.660309
Log-likelihood     3       1.53541   0.674123



In [40]:
print(res.expected_df)


Expected frequency counts

        East      West     North     South
--  --------  --------  --------  --------
 0   42.7653   146.813   131.118   72.3042
 1  442.235   1518.19   1355.88   747.696



In [41]:
import numpy as np
from scipy.stats import chi2_contingency

In [43]:
observed = np.array([[50,142,131,70],[435,1523,1356,750]])
chi_val, p_val, dof, expected = chi2_contingency(observed)
chi_val, p_val, dof, expected 

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [45]:
chi_val, p_val, dof, expected = chi2_contingency(observed, correction=False)
chi_val, p_val, dof, expected

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [46]:
chi_val, p_val, dof, expected = chi2_contingency(observed, lambda_='log-likelihood')
chi_val, p_val, dof, expected

(1.5354067803116846,
 0.6741229013112389,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

# Q4

In [47]:
rj = pd.read_csv('Costomer+OrderForm.csv')
rj.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [48]:
rj.describe()

Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [49]:
rj.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Phillippines  300 non-null    object
 1   Indonesia     300 non-null    object
 2   Malta         300 non-null    object
 3   India         300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB


In [50]:
rj.dtypes

Phillippines    object
Indonesia       object
Malta           object
India           object
dtype: object

In [51]:
table = [[271,267,269,280],[29,33,31,20]]

In [53]:
data0 = pd.DataFrame([
    [271,267,269,280],
    [29,33,31,20]],
    index = ['Error Free', 'Defective'], columns = ['Phillippines','Indonesia','Malta','India'])
data0

Phillippines  Indonesia  Malta  India
Error Free           271        267    269    280
Defective             29         33     31     20

In [54]:
res = stat()
res.chisq(df=data0)
print(res.summary)


Chi-squared test for independence

Test              Df    Chi-square    P-value
--------------  ----  ------------  ---------
Pearson            3       3.85896   0.277102
Log-likelihood     3       4.08351   0.252587



In [55]:
print(res.expected_df)


Expected frequency counts

      Phillippines    Indonesia    Malta    India
--  --------------  -----------  -------  -------
 0          271.75       271.75   271.75   271.75
 1           28.25        28.25    28.25    28.25

